from Sys_NCP.TestClass.Test2 import Test2
from Sys_NCP.TestClass.TestLogin import TestLogin
from Sys_NCP.TestClass.SysManage import SysManage
from Sys_NCP.TestClass.CountManage import CountManage
from Sys_NCP.TestClass.ContractQuery import ContractQuery
from Sys_NCP.TestClass.DBCase.NCP_DB_Function import NCP_DB_Function
from Sys_NCP.TestClass.ContractManage.ContractQuery.XN3144_NCP5 import checkMainPageElement
from Sys_NCP.TestClass.ContractManage.ContractQuery.XN3146_NCP6 import ContractQuery_SingleCondition
from Sys_NCP.TestClass.ContractManage.ContractQuery.XN3145_NCP5 import checkContractQueryPageElement
from Sys_NCP.TestClass.ContractManage.ContractQuery.XN3147_NCP6 import ContractQuery_CombinationCondition
from Sys_NCP.TestClass.ContractManage.ContractQuery.XN3148_NCP8 import ContractQuery_FormOperation
from Sys_NCP.TestClass.DBCase.checkMainPageElement import checkMainPageElementDB
from Sys_NCP.TestClass.DBCase.checkPageElement import checkPageElement
from Sys_NCP.TestClass.DBCase.SingleConditionQuery import SingleConditionQuery
from Sys_NCP.TestClass.DBCase.CombinationConditionQuery import CombinationConditionQuery
from Sys_NCP.TestClass.DBCase.FormOperation import FormOperation
from Sys_NCP.TestClass.checkMainPage import CheckMainPage
# from Sys_NCP.TestClass.zsh_casetest import zsh_test